<?php

namespace AppBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTicketsForDate($date){
        $qb = $this->createQueryBuilder('b')
            ->select('SUM(b.nbTicket)')
            ->where('b.dateVisit = :dateVisit')
            ->setParameter('dateVisit', $date)
        ->getQuery();

        return $qb->getSingleScalarResult();
    }
}
