app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: '{_locale}/'
    defaults: {_locale: '%locale%'}
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fr
        permanent: true